set -g default-terminal "xterm-256color"
bind-key -n C-j split-window -h
bind-key -n C-k split-window -v
bind-key -n C-Left select-pane -L
bind-key -n C-Right select-pane -R
bind-key -n C-Up select-pane -U
bind-key -n C-Down select-pane -D
bind-key -n C-l select-pane -l
set -g mouse on 
