dotfiles_dir = "Desktop/dotfiles"

[settings]
prehooks = [ "mkdir -p ~/.zsh", "mkdir -p ~/.config/Code/User" ]

[settings.dots]
gitconfig = { source = "gitconfig", target = ".gitconfig" }
npmrc = { source = "npmrc", target = ".npmrc" }
tmuxconf = { source = "tmuxconf", target = ".tmux.conf" }
vimrc = { source = "vimrc", target = ".vimrc" }
zshrc = { source = "zshrc", target = ".zshrc" }
zsh_init = { source = "zsh/init.zsh", target = ".zsh/init.zsh" }
code_config = { source = "vscode.json", target = ".config/Code/User/settings.json" }
brownie_config = { source = "brownie.yaml", target = "brownie-config.yaml" }
gnupg_config = { source = "gnupgconf", target = ".gnupg/gpg-agent.conf" }