dotfiles_dir = "Desktop/dotfiles"

[settings]
prehooks = [
    "/usr/bin/mkdir -p ~/.gnupg",
    "/usr/bin/mkdir -p ~/.zsh",
]

[settings.dots]
brownie_config = { source = "individual/brownie.yaml", target = "brownie-config.yaml" }
gitconfig = { source = "individual/gitconfig", target = ".gitconfig" }
gnupg_config = { source = "individual/gnupgconf", target = ".gnupg/gpg-agent.conf" }
npmrc = { source = "individual/npmrc", target = ".npmrc" }
tmuxconf = { source = "individual/tmuxconf", target = ".tmux.conf" }
vimrc = { source = "individual/vimrc", target = ".vimrc" }
zshrc = { source = "zsh/zshrc", target = ".zshrc" }
zsh_init = { source = "zsh/init.zsh", target = ".zsh/init.zsh" }

[profiles.remote]
prehooks = [
    "/usr/bin/mkdir -p ~/.config/systemd/user",
    "/usr/bin/sudo /usr/bin/rm -f /etc/systemd/system/autorestic@.service",
    "/usr/bin/sudo /usr/bin/rm -f /etc/systemd/system/autorestic@remote.timer",
    "/usr/bin/sudo /usr/bin/rm -f /etc/systemd/system/backup-mailcow.service",
    "/usr/bin/sudo /usr/bin/rm -f /etc/systemd/system/backup-mailcow.timer",
    "/usr/bin/sudo /usr/bin/systemctl daemon-reload",
]
posthooks = [
    "/usr/bin/sudo /usr/bin/ln -s ~/.config/systemd/user/autorestic@.service /etc/systemd/system/autorestic@.service",
    "/usr/bin/sudo /usr/bin/ln -s ~/.config/systemd/user/autorestic@remote.timer /etc/systemd/system/autorestic@remote.timer",
    "/usr/bin/sudo /usr/bin/ln -s ~/.config/systemd/user/backup-mailcow.service /etc/systemd/system/backup-mailcow.service",
    "/usr/bin/sudo /usr/bin/ln -s ~/.config/systemd/user/backup-mailcow.timer /etc/systemd/system/backup-mailcow.timer",
    "/usr/bin/sudo /usr/bin/systemctl daemon-reload",
    "/usr/bin/systemctl --user daemon-reload",
]

[profiles.remote.dots]
autorestic_service = { source = "services/autorestic@.service", target = ".config/systemd/user/autorestic@.service" }
autorestic_timer = { source = "services/autorestic@remote.timer", target = ".config/systemd/user/autorestic@remote.timer" }
backup_mailcow_service = { source = "services/backup-mailcow.service", target = ".config/systemd/user/backup-mailcow.service" }
backup_mailcow_timer = { source = "services/backup-mailcow.timer", target = ".config/systemd/user/backup-mailcow.timer" }
space_check_service = { source = "services/space-check.service", target = ".config/systemd/user/space-check.service" }
space_check_timer = { source = "services/space-check.timer", target = ".config/systemd/user/space-check.timer" }
space_warn_service = { source = "services/space-warn.service", target = ".config/systemd/user/space-warn.service" }
syncthing_service = { source = "services/syncthing.service", target = ".config/systemd/user/syncthing.service" }